### ISSUE TITLE
StockSolution message?

### ISSUE THREAD

**Issue by skearnes** [Open-Reaction-Database/ord-schema#108]
#100 brought up an interesting question about the `Concentration` message being unused in the current schema. Here's a potentially bad idea:

Add a `StockSolution` message as a field for `ReactionInput`. This message might have a structure like:

```
message StockSolution {
  Compound solute = 1;
  Compound solvent = 2;
  Concentration concentration = 3;
  Volume amount = 4;
}
```

This use case is common enough that forcing translation to molar amounts---even via a helper function---seems overly burdensome. This would allow the user's input to be closer to what is represented in the schema; it might be hard for users to inspect the programmatic translation to moles, for instance, but they could easily verify the `StockSolution` values.

The obvious downside is that this effectively ignores the `amount` field for the `Compound` messages. But I might be okay with that for such a common use case...?

**Comment by skearnes** [comment]
The stock_solution helper function feels a bit different to me than the build_compound or other functions, since it's not actually building a message of that type; it's doing a lot of indirection that maybe we should just make part of the schema.

**Comment by connorcoley** [comment]
I'm particularly averse to concentrations because they represent derived properties unless you purchase pre-mixed stock solutions at a known concentration. A stock solution is really the result of mixing certain amounts of multiple components together. 

Re: this proposal, I don't like the idea of structuring the same underlying information (what was physically added) in two different formats. An early version of the schema _did_ use the concentration field, but it created ambiguity as to which fields should be defined. It made stock solutions this special class of solutes and solvents rather than a sum of `components`. 

Also note that in your example, `solute` and `solvent` should really be repeated fields. If we have a stock solution that uses two solutes and one solvent, does `concentration` need to be repeated as well? For multiple solvents, how do we capture different volume ratios? These questions are what prompted me to collapse everything into one `components` field.

I absolutely agree that the helper function feels different because it's not building a message. At a minimum, a name change (`set_solute_moles(Compound: solute, List[Compound]: solvents, string: concentration)`?) would be appropriate.

**Comment by skearnes** [comment]
These are all good points. Part of me wonders if this means that we shouldn't be providing a helper function at all? It's essentially enabling people to use this derived concentration value to further derive the amount, when it sounds like they should be going back to the creation of the stock solution itself? I noticed that the SI for the Nielsen example includes moles rather than "such and such volume of a 10 mM stock solution", so that obviates the need for the helper.

From the user perspective, are bench chemists going to be thinking more in terms of stock solution volumes or moles? I think I'd prefer that we avoid including derived values in the schema at all, but using a derived concentration value that matches what the chemist would write in their SI seems less sinful than using a moles value that was derived from a likewise-derived concentration value?

**Comment by skearnes** [comment]
(Also, how common are stock solutions with more than one solute? I have no idea.)

**Comment by connorcoley** [comment]
I do think the helper function is still useful to take care of simple math. This is especially useful for small scale HTE where measurements aren't terribly precise anyway.

> are bench chemists going to be thinking more in terms of stock solution volumes or moles?
They will either think about moles and volume (e.g., 0.1 mmol of _x_ in 5 mL of _y_) or concentration and volume (e.g., 5 mL of a 20 mM solution of _x_ in _y_).

> (Also, how common are stock solutions with more than one solute? I have no idea.)
Not especially common, but I don't think we want the schema to be incapable of describing them in a structured format.

**Comment by skearnes** [comment]
OK, I'm fine requiring that the schema representation be "x mmol of A in y mL of B" and providing a helper function to get this from a "x mL of a y mM solution of A in B" description. It seems common enough to write things this way that nobody will be shocked that we don't put concentrations into the schema.
