### ISSUE TITLE
Grouping serialized protos

### ISSUE THREAD

**Issue by skearnes** [Open-Reaction-Database/ord-schema#109]
Based on https://github.com/Open-Reaction-Database/ord-schema/pull/106#discussion_r414834950 and related to #73.

There are several mechanisms available for grouping serialized messages into database-like objects. Two that have been specifically designed for protos are [LevelDB](https://github.com/google/leveldb) and [TFRecords](https://www.tensorflow.org/tutorials/load_data/tfrecord).

LevelDB is nice because it stores `key->value` pairs to enable constant-time lookup by key. However, its file structure is a directory containing multiple files and its python APIs are third-party only (e.g. [plyvel](https://github.com/wbolster/plyvel)). It's not clear to me how/if LevelDB handles sharding of large databases, but this might not be an issue for us.

TFRecords provides a single file and has first-party python support, but does not allow for key-based lookup.

**Comment by skearnes** [comment]
Suggested uses:
1. Make datasets of Reaction examples available through one of these mechanisms.
2. Have each submission be represented by one of these databases.

Due to the simpler API, TFRecords is probably the way to go. We lose fast lookup, but most datasets will be small enough that traversing the set won't be a huge issue?

**Comment by connorcoley** [comment]
I'd prefer to avoid more dependencies (even if it is Tensorflow).

What about the `Dataset` message type you had proposed earlier? The database could consist of `ord-dataset-###########.pb` files that each can be parsed into one `Dataaset`. One-off reaction entries could still be uploaded as single-reaction datasets.

**Comment by skearnes** [comment]
That's a good idea, too. We would avoid the block size issues that way (since it would just be one file) and it would simplify the scripts if they only had to open a `Dataset` message and iterate over it instead of looping over a set of individual files. Submissions of individual reactions could be grouped into a `Dataset` as the first step of the validation...

Thoughts?

**Comment by connorcoley** [comment]
I do like having dataset grouping as a natural part of the storage. I'd rather have an HTE scientist prepare one `.pb` than a .zip of >1000 separate files for submission. I also think that in a dream scenario where bench chemists prepare data as part of an SI submission, creating one `Dataset` (or at least a small number) for the whole publication is ideal.

The ML-preprocessing script integration is also cleaner with this organization. You associate a preprocessing script with a single `Dataset` identifier rather than a long list of individual reactions that have to be aggregated.

In another dream scenario where we have a working webform and user authentication, a chemist could stage `Reaction` data into a draft `Dataset` while working on a project. When they're ready to package it up and publish, they simply submit that one `Dataset`. 

One question this raises is whether `provenance` should be moved to the dataset level. My vote is no (because, e.g., user2 might fix a typo in one of user1's reactions as part of a larger dataset) but I figured I'd bring it up.

**Comment by skearnes** [comment]
Excellent; I resurrected #62 to try this out (working on tests and such now).

>One question this raises is whether provenance should be moved to the dataset level. My vote is no (because, e.g., user2 might fix a typo in one of user1's reactions as part of a larger dataset) but I figured I'd bring it up.

Good question. I agree that we should keep per-`Reaction` provenance information. We can include some things like a link to the original PR in the `Dataset` description if we want.

**Comment by skearnes** [comment]
It sounds like you're leaning toward requiring that submissions be in `Dataset` form rather than individual files? Do you want to require that or allow individual files as well?

**Comment by skearnes** [comment]
(We could provide a simple script that will group a set of Reaction files into a Dataset.)

**Comment by skearnes** [comment]
One potential risk: would we ever encounter a `Dataset` that is too large to be loaded into memory? This could occur before we've removed the large bytes fields.

**Comment by connorcoley** [comment]
I am leaning toward submissions being in `Dataset` format, yes. A single `Reaction` could be automatically packaged into a single-reaction `Dataset`. 

> One potential risk: would we ever encounter a Dataset that is too large to be loaded into memory? This could occur before we've removed the large bytes fields. In that case we'd probably want the files to stay separate until after the bytes data is removed.

That's a valid concern. But wouldn't the submitter also have trouble loading it into memory? Perhaps submission would involve uploading (a) one or more `Dataset`s, (b) one or more `Reaction`s that would automatically be aggregated into one `Dataset` after validation. Files in use case (b) could be uploaded one at a time

**Comment by skearnes** [comment]
I like these options; sharding into separate Dataset messages and then combining them in the submission pipeline after removing the large bytes data sounds good to me.
