### ISSUE TITLE
Scripts in protos

### ISSUE THREAD

**Issue by skearnes** [Open-Reaction-Database/ord-schema#144]
We have a few places where scripts are allowed to be stored in `Data` messages, especially for automation and ML preprocessing. For both readability and security, what would you think about replacing these `Data` messages with `string url` fields pointing to e.g. colab/jupyter notebooks---or even a blog post about how to build a model with these data?

This would sidestep the security issues of including executable code as part of the record, as well as allow for folks to easily update their scripts without needing to change the records in the database. I think it nicely decouples the data from the downstream applications in ways that are not possible with `Data` messages.

**Comment by skearnes** [comment]
Additionally, this will ease the review burden by avoiding having to check that the code works, or really even worrying about that aspect of downstream usage---it would improve readability and more clearly emphasize the data itself during review.

**Comment by connorcoley** [comment]
Some thoughts:

1. I agree that it will be easier to review submissions if we don't have to look at this code. Plus, readability is an important consideration since big multi-line strings will look sloppy in the pbtxt format.

1. We will potentially lose some permanence (if that's the right word) by having scripts only exist through url pointers. How do we know that someone won't delete their public GitHub repo, gist, or Colab notebook where the example was kept? I recognize that we also have this limitation for our other `string url` fields.

1. Is it a security issue to have executable code if we never automatically execute it? 

1. I think it's possible for these scripts to become dated over time. For example, suppose we had an example of someone building a ML model with Theano. Would we want to eventually overwrite that script with a Tensorflow or Pytorch equivalent? What if Pandas falls out of fashion after we've defined a convention of preparing pandas dataframes?

1. The current use of a `map` does mean we have to define naming conventions, which I don't like. 

1. I think we will want to allow multiple URLs or pointers to examples of the data usage. We might want to allow a string description. 

What do you think about creating another message?

```
message Dataset {
  string name = 1;
  string description = 2;
  repeated Reaction reactions = 3;
  repeated DatasetExample examples = 4;
  string dataset_id = 5;
}

message DatasetExample {
  string description = 1;
  string url = 2;
  RecordEvent example_created = 4;
}
```

Optionally, we could add a `Person` or `RecordEvent` field to the `DatasetExample` as a way of rewarding people who create/contribute examples that way. I assume we'll want to solicit contributions of examples and should give proper attribution. That would (should) involve moving `RecordEvent`s out to be a top-level message, rather than part of `ReactionProvenance`.

**Comment by skearnes** [comment]
> Some thoughts:
> 
> 1. I agree that it will be easier to review submissions if we don't have to look at this code. Plus, readability is an important consideration since big multi-line strings will look sloppy in the pbtxt format.

+1

> 2. We will potentially lose some permanence (if that's the right word) by having scripts only exist through url pointers. How do we know that someone won't delete their public GitHub repo, gist, or Colab notebook where the example was kept? I recognize that we also have this limitation for our other `string url` fields.

Yes, broken links could be an issue here But I think the benefits of being able to update e.g. colab notebook examples outweigh the risk. We could also check for broken links periodically and prune them from the repo.

> 3. Is it a security issue to have executable code if we never automatically execute it?

I'm less concerned about the security issues of trying to execute the code (since we'd do that in a VM) than I am about the risks posed to downstream users by hosting potentially malicious code. URLs feel safer all around.

> 4. I think it's possible for these scripts to become dated over time. For example, suppose we had an example of someone building a ML model with Theano. Would we want to eventually overwrite that script with a Tensorflow or Pytorch equivalent? What if Pandas falls out of fashion after we've defined a convention of preparing pandas dataframes?

Agreed; another +1 for the URL in this case since it could be updated without needing to update the record in the database.

> 5. The current use of a `map` does mean we have to define naming conventions, which I don't like.

+1

> 6. I think we will want to allow multiple URLs or pointers to examples of the data usage. We might want to allow a string description.
> 
> What do you think about creating another message?
> 
> ```
> message Dataset {
>   string name = 1;
>   string description = 2;
>   repeated Reaction reactions = 3;
>   repeated DatasetExample examples = 4;
>   string dataset_id = 5;
> }
> 
> message DatasetExample {
>   string description = 1;
>   string url = 2;
>   RecordEvent example_created = 4;
> }
> ```
> 

I think this is a fantastic idea.

> Optionally, we could add a `Person` or `RecordEvent` field to the `DatasetExample` as a way of rewarding people who create/contribute examples that way. I assume we'll want to solicit contributions of examples and should give proper attribution. That would (should) involve moving `RecordEvent`s out to be a top-level message, rather than part of `ReactionProvenance`.

Yes, that sounds like a good way to give attribution (and also so people know who to contact if something breaks).
