### ISSUE TITLE
RSC chemical methods ontology for AnalysisType

### ISSUE THREAD

**Issue by dcambie** [Open-Reaction-Database/ord-schema#152]
Congratulations on this project :)
I have a small consideration.

Currently, in the `ReactionAnalysis` message, the `AnalysisType` enum lists 17 values.
https://github.com/Open-Reaction-Database/ord-schema/blob/b8dfae2e3ea3d4a011cfcfdbcab79b501d6398af/proto/reaction.proto#L678-L695

However, many different analytical techniques can be used to characterize a reaction. To this end, what about using the RSC ontology for chemical methods[1]?
e.g. a new CHMO ID field could be adopted instead of adding new values to the AnalysisType enum.

[1] https://github.com/rsc-ontologies/rsc-cmo
See for example [LC-DAD](https://www.ebi.ac.uk/ols/ontologies/chmo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHMO_0001738&viewMode=All&siblings=true)

**Comment by skearnes** [comment]
Thanks for the suggestion! I'll let @connorcoley weigh in on this since he's got the best perspective on the diversity of methods here. My main concerns are that it adds another level of complexity for users to have to find their approach in the system and downstream applications may not be able to profitably distinguish between methods at that resolution.

A possible alternative would be to modify the schema to make this an optional specification; for example adding a `int32 chmo_id` field (possibly as a `oneof` with AnalysisType unless we allow the user to specify both).

**Comment by connorcoley** [comment]
I agree that our `AnalysisType` enum covers a very limited list compared to the CHMO ontology. I like the suggestion of having an optional `int32 chmo_id` field to allow this greater degree of flexibility. I also agree with Steve that users may not want to deal with that increased level of complexity, so allowing both to be defined would be find with me. I'll submit a quick PR
