### ISSUE TITLE
Submission/data repos

### ISSUE THREAD

**Issue by skearnes** [Open-Reaction-Database/ord-schema#154]
I'd initially been thinking that we should have separate repositories for submissions and official data. Lately I've been leaning toward a single-repo model. Now that we have adopted the `Dataset` framework there seems little need to have a completely separate repo to e.g. reorganize the data. If we want to make changes like adding RDKIT_BINARY values to the official data, we could just create a PR on the single repo. I also like the idea of preserving the commit history from the submissions.

Thoughts? Any reason we'd want a separate repo with its own history?

**Comment by connorcoley** [comment]
I agree that two separate repos might be unnecessary. I like having the commit history from submissions more easily accessible via the official repo (rather than having to refer back to the submission repo). 

I think I would like to have the `RDKIT_BINARY` values be part of the official repo, but I'm not sure how to balance that with the lack of readability in the pbtxt format

**Comment by skearnes** [comment]
Decision: one repo; RDKIT_BINARY won't be added intentionally for now for versioning reasons.
