### ISSUE TITLE
Ambiguous defaults in the schema

### ISSUE THREAD

**Issue by skearnes** [Open-Reaction-Database/ord-schema#156]
Proto3 changed a lot of things, including the ability to [check that non-message fields are set to their default values](https://developers.google.com/protocol-buffers/docs/proto3#default) and [set custom defaults](https://stackoverflow.com/a/33229024).

However, I don't think this will be a problem for us since most (all?) of the ambiguous fields are contained in submessages that *do* indicate when they have been set to their defaults. For example:

```python
message = reaction_pb2.ReactionOutcome()
print(message.HasField('conversion')  # --> False
message.conversion.value = 0.0
print(message.HasField('conversion')  # --> True
```

So even though the `value` is not serialized because it matches the default, the `conversion` field *is* serialized as an empty (default) message:

```python
print(message)  # --> conversion {}

**Comment by connorcoley** [comment]
That's good to know. And this behavior (the ability to check with `HasField`) is retained after serialization/deserialization? 

The other question would be whether this significantly detract from the readability of the pbtxts and if, upon exporting the data to BigQuery for visualization/search, BigQuery can distinguish these two cases

**Comment by skearnes** [comment]
> That's good to know. And this behavior (the ability to check with `HasField`) is retained after serialization/deserialization?
> 

Yes:

```python
new = reaction_pb2.ReactionOutcome()
print(new.HasField('conversion'))  # --> False
text_format.Parse(text_format.MessageToString(message), new)
print(new.HasField('conversion'))  # --> True
```

> The other question would be whether this significantly detract from the readability of the pbtxts and if, upon exporting the data to BigQuery for visualization/search, BigQuery can distinguish these two cases

Good questions. I don't think the readability is bad enough to justify moving to JSON...do you agree? I'll need to check for BigQuery; worst case we can manually fill in the default value when generating the BigQuery input JSONL file.

**Comment by connorcoley** [comment]
> I don't think the readability is bad enough to justify moving to JSON...do you agree?

I agree, as long as we can provide a sufficiently clear explanation/documentation for users. I think for a casual user looking to scrape data from a `Reaction`, their instinct will be to look at `outcome.conversion.value` rather than first check `if outcome.HasField('conversion')`

How averse are you to defining a default values in general? Just because yield/conversion are going to be so frequently used, and because we would love to capture 0% conversion and 0% yield cases, I might still suggest a default value of -100 for a Percentage value.

**Comment by michaelmaser** [comment]
An indication of intention seems important. Or perhaps having numerical values be consistently intentional, with a default of `UNSPECIFIED` or `UNKNOWN` or `UNQUANTIFIED`. Very often a numerical conversion isn't really known unless remaining starting material is actually quantified, which doesn't always happen. Assuming a numerical conversion seems dangerous.

**Comment by connorcoley** [comment]
Would trying to access certain fields/subfields during (a) validation or (b) text-generation cause those messages to be created and remove our ability to distinguish specified v. unspecified? I think the way we recursively do validation is okay, but text generation might be a problem.

**Comment by skearnes** [comment]
We should write some tests for this; I'll add some for the validation side of things.

**Comment by skearnes** [comment]
Digging deeper into this: there's experimental support for presence tracking in protobuf 3.12!

https://github.com/protocolbuffers/protobuf/releases/tag/v3.12.0
https://github.com/protocolbuffers/protobuf/issues/1606#issuecomment-618687169

I'll play around with this and try to make it stick. If it doesn't end up working for some reason, I recommend that we downgrade to `proto2`.

**Comment by skearnes** [comment]
Reopening pending JS support for `optional` fields.
