### ISSUE TITLE
Database backend for the editor

### ISSUE THREAD

**Issue by skearnes** [Open-Reaction-Database/ord-schema#356]
Disadvantages:
* Complexity relative to our current solution (local filesystem).

Advantages:
* Consistent writes.
* Faster?
* Much better aligned with industry standards.
* If we set it up the right way we can use a centralized database on GCP and have the load balancer direct traffic to more than one instance.

**Comment by antonkast-google** [comment]
The current editor is not designed for concurrent access to any dataset. There is no way for a user to navigate to someone else's data, so I am not convinced consistency is a concern.

Similarly, the scenario where we need a distributed service is one where concurrent users become CPU-bound. We have control over the scaling because we invite people to use it, we can ask them to stop, and to my knowledge our monthly active user count is zero. I find it difficult to see this as a pressing concern.

Clearly the conventional design would be to have a database for consistency and load-balanced nodes for scaling the rendering compute. If someone feels like working on this, I support them. Otherwise, I think the question is when to do it.

I speculate validation will be the most common frontend request since it happens whenever a user modifies anything. When I click "validate" on our current frontend at editor.open-reaction-database.org, I observe 50 validation requests which are handled at a rate of about 10 Hz. Back of the envelope, if a user modifies 1 field per second, we can handle 10 users editing reactions at once before we start queueing.

I suggest we deal with this as soon as we observe two users on the site at the same time.

**Comment by skearnes** [comment]
Fixed by #462

**Comment by antonkast-google** [comment]
Note that #462 is not yet deployed.
