### ISSUE TITLE
Cookies are reset when entering reviewer mode

### ISSUE THREAD

**Issue by skearnes** [Open-Reaction-Database/ord-schema#419]
If you navigate to `/review` and load one of the submitted datasets, the user cookie is reset to `.review/<pr_number>`. This means that when you are done reviewing, you cannot return to the datasets you were editing previously (if any).

I spent some time refactoring `serve.py` to always take the user from the the URL, but this approach ran into a roadblock with the javascript functions in `dataset.js` that only refer to the cookie for dataset read/write operations. We could:

1. update these functions to use the URL user (and _only_ use the cookie to set the URL user when it is not provided), 
2. use this as another reason to move to GitHub-based authentication sooner, or
3. copy a bunch of code and modify it such that the read-only review mechanism does not try to reuse code from the normal editor workflow.

I'm leaning toward option 1, personally. WDYT?

**Comment by skearnes** [comment]
@antonkast-google @connorcoley

**Comment by antonkast-google** [comment]
The nice thing about having the user in the URL is it lets people share links, e.g. when reporting bugs.

The nice thing about having the user in the cookie is people can use http://editor.open-reaction-database.org/ instead of bookmarking their UUID.

I don't know what /review is for, so I don't think I can offer an opinion. But if the question is what to do when the user in the URL and the user in the cookie disagree, the policy I remember is that the URL should win but not clobber the cookie so that these nice benefits will persist.

Why must /review clobber the user cookie?

**Comment by skearnes** [comment]
Thanks; currently the URL does clobber the cookie: https://github.com/Open-Reaction-Database/ord-schema/blob/main/editor/py/serve.py#L682

My local changes make it so this doesn't happen, but then that breaks the dataset read/write mechanics, which depend on the cookie being correct.

**Comment by antonkast-google** [comment]
I see! So my memory was wrong, and the problem you describe explains the current implementation.

What we call "user" is really just a namespace for datasets. We think of it as an access control because user IDs are obscure, but everything is actually world-writable. The identifier belongs in a URL, not a cookie, so option (1) is the right answer. It will be a hassle to copy the identifier from the URL into every XHR, but I think it's the right thing to do. (Copying the code sounds bad, and I don't see how authentication would help.)

Maybe easier to comprehend would be:

1) eliminate "user" in favor of a globally unique identifier for datasets; and
2) communicate the identifier in URLs as a path component;
3) thread the identifier through every XHR; and
4) postpone access controls until we define a structure that binds datasets to users and permissions.

**Comment by skearnes** [comment]
I agree that option 1 is the best place to start.

Authentication would solve the scoping problem. Cookies are brittle because if I restart chrome all my cookies disappear and I can't get back to the datasets I was editing (b/c I have selected to delete cookies when chrome exits). We need some sort of scoping even if we use globally unique dataset identifiers so that users only see (and edit) the datasets they "own".

So I think we should start doing our diligence about GitHub authentication. If it turns out to be easy, let's just do it now instead of building in more hacks.

**Comment by skearnes** [comment]
Additional reason: authentication allows for users to work on multiple devices.

**Comment by skearnes** [comment]
This should be resolved by #462
