### ISSUE TITLE
Provenance

### ISSUE THREAD

**Issue by skearnes** [Open-Reaction-Database/ord-schema#44]
We need to keep track of enough information to handle (at least) the following cases:

- Person A ran an experiment and Person B created the proto describing it.
- Person C made a mistake while creating a record and submits a correction.

Keeping pointers to the original submission artifacts will cover many of these cases, but we probably need to expand the `Provenance` message to contain these pointers and additional information about the submitter/creator (not just the experimenter). The guiding principle, I think, is "do we know who we should talk to if there's a problem?"

Related to this is the question of duplicates (we may just want to ignore these?):

- Person E and Person F both extracted the same reaction from a publication (possibly with slightly different details or even enum values).

**Comment by connorcoley** [comment]
I agree, if we want to keep that bookkeeping _with_ the protos themselves rather than in an auxilliary database (e.g., that assigns a unique ID to each proto and logs all of the edits).

Re: expanding the ```Provenance```, should we have a ```repeated RecordModification modifications``` where a ```RecordModification``` contains a DateTime, Person, and maybe a ```string details```?

Not sure about duplicates. We may want to ignore that problem for now. I don't know how many people will actually go back through historical data.
