### ISSUE TITLE
Separate internal standards from products

### ISSUE THREAD

**Issue by connorcoley** [Open-Reaction-Database/ord-schema#511]
Listing internal standards as a product (e.g., for the sake of reporting raw UV areas) might lead to unusual reaction SMILES strings. We could separate out internal standard measurements in a separate `repeated ReactionProduct standards` field. I'm not completely sure if this is the best way to structure it.

**Comment by michaelmaser** [comment]
I'm not sure it is either. I don't know that `ReactionProduct` is the right message, there's a lot of extraneous info (`is_desired_product`, `isolated_color`, `texture`, maybe `features`). 

Are we opposed to adding something like an `AnalyticalStandard` message? Could retain `identifiers`, `amount`, and `measurements`, and have, e.g., a `oneof kind INTERNAL or EXTERNAL`. Could also use a `Compound` in place of `identifiers` and `amount` so `source` can be specified too, though this also has extraneous info. Similar dilemma we had with the `ReactionProduct` message. Thoughts?

**Comment by skearnes** [comment]
I'm a bit confused about which problem we're trying to solve. From Connor's comment it sound like the problem is that we have internal standards listed as inputs _and_ products without a good way of distinguishing them from the more interesting products.

But it sounds like Mike is suggesting that these standards shouldn't be listed as standard inputs in the first place?

**Comment by michaelmaser** [comment]
I think they should be listed as standard inputs so that they’re part of the reaction procedure. I think they need to be distinguished from products so they don’t confound the reaction SMILES/list of reaction products. That said, I think they could/should be handled similarly to products since we want to record measurements for them.

**Comment by connorcoley** [comment]
Could this be addressed by adding a `reaction_role`-esque field back in to a Product? That would also make it easy to annotate what should be considered a leftover reactant v. internal standard v. a "real" product

**Comment by michaelmaser** [comment]
I think that sounds good

**Comment by michaelmaser** [comment]
>Could this be addressed by adding a `reaction_role`-esque field back in to a Product?

I actually think I like the exact structure of `Compound.ReactionRole` for this. The `ReactionRoleType`s capture every post-reaction species isolation/observation scenario I can think of, besides `PRODUCT`, of course. 

Couple questions:

1. Are we able to borrow a sub-message this way? I.e., could we add `Compound.ReactionRole.ReactionRoleType reaction_role` to `ReactionProduct` (/`ProductCompound`)? Or, would we have to shift that to a higher-level message to then reuse it? Either way, if it can be reused, should we just add `PRODUCT` back to the `ReactionRoleType` enum?
2. If not and we need to write a new "`AnalyteRole`" type message, we could include `PRODUCT` and rename some of the current roles to `RECOVERED_<role>`, e.g., `RECOVERED_REACTANT`, `RECOVERED_CATALYST`, etc.

Thoughts?

**Comment by skearnes** [comment]
It's possible to use `Compound.ReactionRole.ReactionRoleType` but I think we'd want to pull it out for consistency here.

That seems like an elegant solution if it will cover all the bases here.

**Comment by connorcoley** [comment]
+1 to pulling out ReactionRole to be higher-level and adding PRODUCT back in
