### ISSUE TITLE
Product amounts: Should they be ProductMeasurement entries?

### ISSUE THREAD

**Issue by skearnes** [Open-Reaction-Database/ord-schema#514]
`ReactionProduct` has an `Amount` field; should amounts instead be captured as `ProductMeasurement` entries paired with e.g. a `WEIGHT` analysis? We could move the `Amount` field to `ProductMeasurement`.

Are products ever measured in non-mass units? Should the AnalysisType `WEIGHT` be changed to `AMOUNT` or have separate `MASS` and `VOLUME` entries?

**Comment by michaelmaser** [comment]
I think I'm fine with this. 

I think we may have discussed/settled on a reason to retain `Amount` in the `ReactionProduct` when formulating the schema update. @connorcoley, do you remember what this was, if anything? 

One possible benefit to having `Amount` directly within `ReactionProduct` is to reduce nesting when using the `Amount` in, e.g., a next-step `ReactionInput` definition or if using it to calculate yield programmatically (not sure anyone will do this). Otherwise, I agree this could be considered redundant.

>We could move the `Amount` field to `ProductMeasurement`.

Is there a reason to retain `Amount` at all? If a `WEIGHT` analysis can be used as an `analysis_key` for a `YIELD` type `ProductMeasurement`, does there need to be a separate field? Would there be any other use for a product's `Amount` besides to measure yield? (e.g., if the `ReactionProduct` message is being used for something that isn't a product (#511 )) If so, could it be captured by just adding to the `MeasurementType` enum?

>Are products ever measured in non-mass units?

I'm not concretely aware of non-mass measurements for products. There may be, e.g., process chemistry applications that make so much of a compound they measure in volume, but I'm not sure that's even very common.

**Comment by skearnes** [comment]
Thanks @michaelmaser; in that case I'll amend my proposal to adding a `Mass` message to `ProductMeasurement`. 

Any reason to change `WEIGHT` to `MASS` in `Analysis`, or is that difference useful since it reflects the use of a physical scale?

**Comment by connorcoley** [comment]
> I think we may have discussed/settled on a reason to retain Amount in the ReactionProduct when formulating the schema update. @connorcoley, do you remember what this was, if anything?

It was because it's not unheard of to report amounts of products in mmol; the "amount" could be derived from a measurement other than an isolated weight. We decided that if we were going to allow product quantities to be defined by mass or moles, a full `amount` message was justified. 

I was about to write a defense of keeping `amount` at the highest level in the product but realized that it _is_ just a derived amount from, most often, an isolated weight. 

> in that case I'll amend my proposal to adding a Mass message to ProductMeasurement.

This is starting to sound inconsistent. We decided to keep all "analytical data" in the analysis message, even if it corresponded to a presumably-isolated compound, like a melting point Temperature, isolated weight Mass, circular dichroism Angle, etc. However, an exception might be justified for this special case of Mass since it's so common.

**Comment by michaelmaser** [comment]
>in that case I'll amend my proposal to adding a `Mass` message to `ProductMeasurement`.
>>This is starting to sound inconsistent. We decided to keep all "analytical data" in the analysis message...

>I think we may have discussed/settled on a reason to retain `Amount` in the `ReactionProduct`...
>>It was because it's not unheard of to report amounts of products in mmol; the "amount" could be derived from a measurement other than an isolated weight.

Could this all perhaps be handled by removing the `Amount` message and just adding `AMOUNT` to the `MeasurementType` enum? That way:

1. all the "analytical data" stays in the analysis 
2. analyses other than isolated weight (`WEIGHT`) could also be used to specify "amount" in any unit (mass from `WEIGHT` (or `MASS`), moles from e.g. `NMR_1H`, etc. Adding `VOLUME` in the `AnalysisType` enum as @skearnes suggested could catch any rare cases of mL / L amounts)
3. an "amount"-based analysis doesn't have to be tied to a `YIELD` measurement

**Comment by skearnes** [comment]
I'm concerned that just adding an `AMOUNT` type drops the units.

I think we should add a `Mass` field to `ProductMeasurement` because it's so common; it's more like the current `Time` field than a complicated structured data message.

I guess the high-level question is whether we want to enforce that amounts/masses are linked to an analysis; if so it seems necessary to remove `Amount` from the `ReactionProduct` level and have something replace it in `ProductMeasurement`.

**Comment by skearnes** [comment]
DIscussed adding `Amount` field to the `oneof` and adding an `AMOUNT` type. Users should be encouraged to report masses over moles, since the latter is derived from the former.

I'll create a PR for review.

**Comment by skearnes** [comment]
Closed by #519
